### ISSUE TITLE
[Request] Add disk metrics?

### ISSUE THREAD

**Issue by Timbus** [marcinbudny/eventstore_exporter#1]
Hi, I'm looking to use this exporter for our eventstore since it looks really good, but unfortunately it doesn't seem to export disk usage stats (as seen under the `/stats/sys` endpoint). 
These stats would be useful for me because I'm using a dedicated EBS disk for the eventstore storage, and EBS has no monitoring by default.

If you could add the 'drive' stats, I'd be very appreciative.
Thanks!

**Comment by marcinbudny** [comment]
Hi, Thank you for the suggestion. I should be able to take a look at this soon.

**Comment by marcinbudny** [comment]
There are now two new metrics `eventstore_drive_total_bytes` and `eventstore_drive_available_bytes` exported in version 0.3.0.

**Comment by Timbus** [comment]
Thank you! This will be very helpful :D
