### ISSUE TITLE
[Request] Add subscriptions metrics

### ISSUE THREAD

**Issue by grigorov** [marcinbudny/eventstore_exporter#2]
Hi, you can add subscriptions metrics? 

in EventStore: 

http://localhost:2113/subscriptions

**Comment by marcinbudny** [comment]
Hi. I can take a look at this in in a week or two. I don't personally use persistent subscriptions, so I'll have to come up with a test environment first. Any particular metrics you would like to see as a result?

**Comment by n-tyulenev** [comment]
Hi, It would be great if there will be list of the subscriptions with stream and group names, number of totalItemsProcessed,totalInFlightMessages, averageItemsPerSecond, count of the opened connections and count of the parked messages (if exists). The latter can be obtained if go via link contained in attribute "parkedMessageUri" (If there's no messages it will return 404)

**Comment by marcinbudny** [comment]
Version 0.4.0 now has metrics related to subscriptions. Items per second can be calculated from total items processed with `rate` function. I did not add metrics related to parked messages. This would require running expensive requests on the EventStore.
