### ISSUE TITLE
httpClient does not pass basic auth when gossip returns IP address

### ISSUE THREAD

**Issue by LukaszRacon** [marcinbudny/eventstore_exporter#20]
In the EventStoreDB setup where `ExtIpAdvertiseAs` is not set `gossip` endpoint returns IP addresses. When `httpClient` hits Slave node - Slave responds with 307 redirect to Master. Since redirect is not going to same domain/subdomain (see https://pkg.go.dev/net/http#Client)  `Authorization` header is not forwarded. 

This results in a failure to retrieve subscriptions stats:
`Atom Pub is disabled and ES version is < 21.2, there is no way to retrieve subscription stats`.

Quick solution is to add `CheckRedirect` and inject basic auth:
```
		esClient.httpClient = http.Client{
			Timeout: config.Timeout,
			CheckRedirect: func(req *http.Request, via []*http.Request) error {
				req.SetBasicAuth(config.EventStoreUser, config.EventStorePassword)
				return nil
			},
		}
```
More elaborate solution would be to add config flag that enables `CheckRedirect` (similar to `config.InsecureSkipVerify`), or to check if address is IP, or use gossip to find Master node.

**Comment by marcinbudny** [comment]
Hi again. I tried to repro the problem using my test cluster environment [here](https://github.com/marcinbudny/eventstore_exporter/tree/master/test_env/20.10-cluster), but haven't hit the problem you're seeing. The test env does not configure advertised addresses and gossip returns IP addresses. Can you provide more details about your setup?

Also from conceptual point of view, a single exporter instance is meant to monitor single ESDB node. So assuming you have multiple ESDB nodes, you would configure one exporter instance for monitoring each of them. A lot of reported metrics make sense only from the perspective of single node. The exporter provides the status about the node and the rest of the cluster "as seen by the monitored node".

**Comment by LukaszRacon** [comment]
Hi Marcin,
Thank you for explanation. 1:1 - metrics to node mapping makes sense. I got deceived by "cluster" mode. 
I run metrics against k8s service which load balanced it across nodes. When exporter hit a Slave node ES returned 307 to Master. Redirect failed since Authorization header is not passed to IP address.

None issue since monitoring each node works fine - thanks again.

**Comment by marcinbudny** [comment]
The "cluster mode" is confusing, that is true. The purpose of this setting is not to query gossip endpoint on single node installations, as this resulted in a timeout on versions <= 20.10. I think this setting will be deprecated when 20.10 goes out of support.
