### ISSUE TITLE
Stream last event number

### ISSUE THREAD

**Issue by rodion-k** [marcinbudny/eventstore_exporter#21]
Is there a metric with the number of the last event of a particular stream?

**Comment by marcinbudny** [comment]
Hey, there is no such metric at the moment. 
Is the intention here to configure one or more stream names, for which the exporter would get the last number of event? 

I assume this is for measuring the subscription gap?

**Comment by rodion-k** [comment]
Hi @marcinbudny, thanks for the reply. Yes, I want to configure multiple stream names. I have catch-up subscriptions for my read models that send their checkpoints to grafana, and I want to measure how far they are from the end of the stream.

**Comment by marcinbudny** [comment]
That makes sense of course. I will put that on my todo list. I also accept contributions if you're interested.

In the meantime, you can export similar metric from the application itself.

**Comment by marcinbudny** [comment]
Added in v0.11.0
