### ISSUE TITLE
Catchup subscription lag

### ISSUE THREAD

**Issue by dneedy** [marcinbudny/eventstore_exporter#3]
We do not seem to get any subscription lag information for our catch up subscriptions.
Information about persistent subscriptions was added in December, is it possible to include catch up ones?

**Comment by marcinbudny** [comment]
I think the server does not track any progress information on catch up subscriptions. The checkpoint is controlled on the client so there you can calculate the gap.

**Comment by dneedy** [comment]
Fair enough
