### ISSUE TITLE
[Feature Request]: Monitor - Subscription / status / # of msgs

### ISSUE THREAD

**Issue by ILyress** [marcinbudny/eventstore_exporter#33]
Hi

I'm trying to add your exporter in my cluster, but I can't find how to monitor the field "Status # of msgs / estimated time to catchup in seconds"  in the subscription panel.

is it possible with this export to monitor this field of subscription panel ? and if not do you intend to add it in a future update pls ?

![Status_of_msgs_estimated_time_to_catchup_in_seconds](https://github.com/marcinbudny/eventstore_exporter/assets/97671511/9aa780e6-6982-4a47-b3ef-aec1a37bd404)

**Comment by marcinbudny** [comment]
Hi,

The values presented in this column are not directly available in the subscription statistics published by the server. However the ESDB UI seems to calculate these values based on other data that sever publishes, and this exporter exports most of it.

So e.g. rate of messages would be calculated from `eventstore_subscription_items_processed_total` metric. Similarly number of messages left to process would be `eventstore_subscription_last_known_event_number - eventstore_subscription_last_processed_event_number`. And then from rate and number of messages to process you'd get the estimated time to catch up.
