### ISSUE TITLE
[Feature Request]: need additional value for clone role to eventstore_cluster_member_is_master metric

### ISSUE THREAD

**Issue by gokcesurenkok** [marcinbudny/eventstore_exporter#4]
Hello , 
it would be nice to see the nodes in clone state , currently as far as i see , value mapping is as like following, 
1 - master
0 - slave 
, 
for the clone nodes it would be nice to have something like this 
1 - master
0 - slave 
2 - clone

Thank you

**Comment by marcinbudny** [comment]
Hi and thank you for the suggestion. I need to check what is available in the API. The current metric specifies "is master" boolean flag, so adding another value to it makes little sense. A new metric may be more sensible, something like "is clone".

PR for this is welcome.

**Comment by gokcesurenkok** [comment]
hi , a new metric is also ok , but you are checking the node role via eventstore_cluster_member_is_master metric in your grafana dashboard, that is why i said so :)

**Comment by marcinbudny** [comment]
The node status metrics have been added in 0.5.0. Grafana dashboard is also updated.
