### ISSUE TITLE
Stats from a single node only on EVS 5.0

### ISSUE THREAD

**Issue by ben-foster-cko** [marcinbudny/eventstore_exporter#5]
Hi, I've deployed the exporter against a v5 cluster, running in cluster mode. However, I'm only seeing stats for a single member rather than all members, for example:

```
eventstore_process_cpu{instance="xxx:43644",job="evs-gwc",service="gateway-eventstore-exporter-qa"}
```

Shouldn't I see a metric for each member of the cluster or is the idea that we have to deploy an instance of the exporter pointing to each node?

**Comment by marcinbudny** [comment]
Hi. You have to deploy a separate instance of the exporter for each cluster node. The `CLUSTER_MODE=cluster` setting only tells the exporter to query the gossip stats endpoint. In single node deployment querying the gossip stats enpoint causes an error, so the `CLUSTER_MODE` variable is just a hint not to do that.
